[pytest]
testpaths = tests
pythonpath = . tests
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient`
    ignore:on_event is deprecated
    ignore:datetime.datetime.utcnow\(\) is deprecated
